title: Project
num: date
icon: 📖

status:
  draft:
    label: Draft
    text: The project is still in draft mode. It can only be seen by editors with panel access.
  unlisted:
    label: In Review
    text: The project is online and can be visited with the direct URL. The team must still give the final go to publish it.
  listed:
    label: Published
    text: The project is online and listed in the blog

columns:
  - width: 2/3
    fields:
      intent:
        type: textarea
      text:
        type: textarea
        size: large

  - width: 1/3
    sections:
      cover:
        type: files
        headline:
          en: Cover Image
          fr: Cover Image
        back: black
        max: 1
        template: cover
      meta:
        type: fields
        fields:
          date:
            type: date
            time: true
            default: now
          author:
            type: users
          category:
            label: Category
            type: select
            default: Project
            options:
              Project: Project
              Observation: Observation
          tags: true
      files:
        type: files
        headline:
          en: Files
          fr: Files